"""empty message

Revision ID: a441b0d50bfd
Revises: e5b1f3f224cc
Create Date: 2026-05-07 12:18:31.046860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a441b0d50bfd'
down_revision: Union[str, Sequence[str], None] = 'e5b1f3f224cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_template', sa.Column('img_path', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_template', 'img_path')
    # ### end Alembic commands ###
